### ISSUE TITLE
Sonarimporter crashes with null pointer exception when there is a component without path.

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#13]
concerning sonarimporter v1.1.3:
If the project in SonarQube has a component without path information then there is the following null pointer exception:

Exception in thread "main" java.lang.NullPointerException
        at de.maibornwolff.codecharta.importer.sonar.SonarComponentProjectAdapter.createNodeName(SonarComponentProjectAdapter.java:63)
        at de.maibornwolff.codecharta.importer.sonar.SonarComponentProjectAdapter.addComponentAsNode(SonarComponentProjectAdapter.java:24)
        at io.reactivex.Flowable.blockingForEach(Flowable.java:5274)
        at de.maibornwolff.codecharta.importer.sonar.SonarImporter.getProjectFromMeasureAPI(SonarImporter.java:37)
        at de.maibornwolff.codecharta.importer.sonar.SonarImporterMain.doImport(SonarImporterMain.java:82)
        at de.maibornwolff.codecharta.importer.sonar.SonarImporterMain.main(SonarImporterMain.java:66)

**Comment by mrpatpat** [comment]
Fixing in branch [bugfix#13](https://github.com/MaibornWolff/codecharta/tree/bugfix%2313)

**Comment by mrpatpat** [comment]
The suggested fix is to null check the path value. If it does not exist, we assume that the name or id (in this order) is the nodes name. 
Since the insertion path is also generated from the path value, the fix assumes that pathless components are inserted at the root node.

**Comment by ukinimod** [comment]
This fix is much better than mine. Thx, mrpatpat!
