### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1322]
```
de.maibornwolff.[secure].importer.sourcecodeparser.e2e.ParseFileToTable > table output has correct metrics for line() FAILED
    java.lang.AssertionError at ParseFileToTable.kt:28

...

65 tests completed, 1 failed
> Task :import:SourceCodeParser:test FAILED
> Task :tools:ccsh:distZip
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':import:SourceCodeParser:test'.
> There were failing tests. See the report at: file:///home/travis/build/MaibornWolff/[secure]/analysis/import/SourceCodeParser/build/reports/tests/test/index.html
``` 

https://travis-ci.org/github/MaibornWolff/codecharta/jobs/732766351

**Comment by BridgeAR** [comment]
At least one e2e test is also flaky:

```
FAIL app/codeCharta/e2e/url.e2e.ts (43.972 s)
  ● [secure] › should throw errors when file parameters in url are invalid and load sample data instead
    TimeoutError: waiting for selector `.md-select-menu-container.md-active > md-select-menu` failed: timeout 30000ms exceeded
      12 | 		await this.clickChooser()
      13 | 
    > 14 | 		await page.waitForSelector(".md-select-menu-container.md-active > md-select-menu")
         | 		           ^
      15 | 		const content = await page.$eval(".md-select-menu-container.md-active > md-select-menu", element => element["innerText"])
      16 | 		return content.split("\n")
      17 | 	}
      at new WaitTask (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
      at DOMWorld.waitForSelectorInPage (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
      at Object.internalHandler.waitFor (node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
      at DOMWorld.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
      at Frame.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
      at Page.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1285:33)
      at FilePanelPageObject.<anonymous> (app/codeCharta/ui/filePanel/filePanel.po.ts:14:14)
      at fulfilled (app/codeCharta/ui/filePanel/filePanel.po.ts:18:24)
          at runMicrotasks (<anonymous>)
```

**Comment by BridgeAR** [comment]
And one more:

```
FAIL app/codeCharta/ui/fileChooser/fileChooser.e2e.ts (39.449 s)
  ● FileChooser › should not load a map and show error, when loading a map with warning and a map with error
    expect(received).toEqual(expected) // deep equality
    Expected: " File is empty or invalid."
    Received: " Minor API Version Outdated. Found: 1.5"
      69 | 		await dialogError.waitUntilDialogIsClosed()
      70 | 
    > 71 | 		expect(await dialogError.getMessage()).toEqual(` ${ERROR_MESSAGES.fileIsInvalid}`)
         | 		                                       ^
      72 | 		await dialogError.clickOk()
      73 | 
      74 | 		await fileChooser.openFiles(["./app/codeCharta/assets/sample3.cc.json"], false)
      at app/codeCharta/ui/fileChooser/fileChooser.e2e.ts:71:42
      at fulfilled (app/codeCharta/ui/fileChooser/fileChooser.e2e.ts:23:24)
          at runMicrotasks (<anonymous>)
```

**Comment by RomanenkoVladimir** [comment]
Can we bump priority to high? The backend test is fixed to my knowledge, however the e2e tests really make development harder and slow down travis even more because we need to constanly rerun jobs

**Comment by BridgeAR** [comment]
The e2e tests still fail regularly.

**Comment by Med-H** [comment]
Do you have Any logs?
