### ISSUE TITLE
OutOfMemory Error using SCMLogParser

### ISSUE THREAD

**Issue by sparkyqin** [MaibornWolff/codecharta#2748]
# Bug
## Actual Behavior
analysis a project using following command
`ccsh scmlogparser git.log --input-format GIT_LOG_NUMSTAT_RAW -nc -o git.cc.json`
then it comes with following exception
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.StringBuffer.toString(StringBuffer.java:669)
        at java.io.StringWriter.toString(StringWriter.java:210)
        at com.google.gson.Gson.toJson(Gson.java:639)
        at de.maibornwolff.codecharta.serialization.ProjectSerializer.getWrappedProject(ProjectSerializer.kt:79)
        at de.maibornwolff.codecharta.serialization.ProjectSerializer.serializeProject(ProjectSerializer.kt:46)
        at de.maibornwolff.codecharta.serialization.ProjectSerializer.serializeProjectAndWriteToFile(ProjectSerializer.kt:32)
        at de.maibornwolff.codecharta.importer.scmlogparser.SCMLogParser.call(SCMLogParser.kt:108)
        at de.maibornwolff.codecharta.importer.scmlogparser.SCMLogParser.call(SCMLogParser.kt:33)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunAll.handleParseResult(CommandLine.java:2413)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2504)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:2454)
        at de.maibornwolff.codecharta.tools.ccsh.Ccsh$Companion.main(Ccsh.kt:73)
        at de.maibornwolff.codecharta.tools.ccsh.Ccsh.main(Ccsh.kt)`
## Expected Behavior
No exception should be thrown

## Specifications
Version: 1.90.0
Platform: Linux

**Comment by ce-bo** [comment]
Thanks for your request @sparkyqin. We are not planning to fix this in our first version of SCMLogParser (the one you used).
Instead, please try SCMLogParserV2. The usage is a bit different but it is more stable. In our next releases we will clearify the namings of both parsers to (SCMLogParser -> SVNLogParser, SCMLogParserV2 -> GitLogParser) in #2350.

Please, let us know if the error still occurs.

**Comment by sparkyqin** [comment]
> Thanks for your request @sparkyqin. We are not planning to fix this in our first version of SCMLogParser (the one you used). Instead, please try SCMLogParserV2. The usage is a bit different but it is more stable. In our next releases we will clearify the namings of both parsers to (SCMLogParser -> SVNLogParser, SCMLogParserV2 -> GitLogParser) in #2350.
> 
> Please, let us know if the error still occurs.

I tried GitLogParser with new version, it works fine. Thank u very much! This is a very nice tool!
