### ISSUE TITLE
ccsh merge throws NoSuchMethodError

### ISSUE THREAD

**Issue by FlorianHoldt** [MaibornWolff/codecharta#2923]
# Question
When calling ccsh merge in order to add custom metrics, I get a java exception complaining about a NoSuchMethodException:
Exception in thread "main" java.lang.NoSuchMethodError: java.io.InputStream.readNBytes(I)[B
        at de.maibornwolff.codecharta.serialization.CompressedStreamHandler.wrapInput(CompressedStreamHandler.kt:14)
        at de.maibornwolff.codecharta.serialization.ProjectDeserializer.deserializeProject(ProjectDeserializer.kt:33)
        at de.maibornwolff.codecharta.filter.mergefilter.MergeFilter.call(MergeFilter.kt:66)
        at de.maibornwolff.codecharta.filter.mergefilter.MergeFilter.call(MergeFilter.kt:14)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2431)
        at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2433)
        at picocli.CommandLine$RunAll.handle(CommandLine.java:2428)
        at picocli.CommandLine$RunAll.handle(CommandLine.java:2389)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunAll.execute(CommandLine.java:2391)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at de.maibornwolff.codecharta.tools.ccsh.Ccsh$Companion.main(Ccsh.kt:82)
        at de.maibornwolff.codecharta.tools.ccsh.Ccsh.main(Ccsh.kt)

## Preparation
I am using CodeCharta 1.101.1

I have Java 9 installed on my machine, this is the output of java -version:
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

Please check these resources first before posting a question

* [/] I searched for answers in [older issues](https://github.com/MaibornWolff/codecharta/issues?utf8=%E2%9C%93&q=)
* [/] I looked into the [README.md](https://github.com/MaibornWolff/codecharta)
* [/] I read the [website](https://maibornwolff.github.io/codecharta/)

**Comment by ce-bo** [comment]
Hi @FlorianHoldt, could you please provide your input files or examples, so that we can reproduce your exact error?
Thank you!

**Comment by FlorianHoldt** [comment]
Hi @ce-bo, I can reproduce this with the example provided in the documentation:
File 1 (demo.cc.json):
{"data":{"projectName":"","nodes":[{"name":"root","type":"Folder","attributes":{},"link":"","children":[{"name":"File.js","type":"File","attributes":{"Metric1":4.0,"Metric2":500.0},"link":"","children":[]},{"name":"service","type":"Folder","attributes":{},"link":"","children":[{"name":"Service1.ts","type":"File","attributes":{"Metric1":40.0,"Metric2":20.0},"link":"","children":[]}]}]}],"apiVersion":"1.3","edges":[],"attributeTypes":{},"blacklist":[]},"checksum":"f082e085beb54395574e2fa2219428df"}

File 2 (demo2.cc.json):
{"data":{"projectName":"","nodes":[{"name":"root","type":"Folder","attributes":{},"link":"","children":[{"name":"File.js","type":"File","attributes":{"Metric3":50.0,"Metric4":1.0},"link":"","children":[]},{"name":"service","type":"Folder","attributes":{},"link":"","children":[{"name":"nested","type":"Folder","attributes":{},"link":"","children":[{"name":"folder","type":"Folder","attributes":{},"link":"","children":[{"name":"Service1.ts","type":"File","attributes":{"Metric3":400.0,"Metric4":200.0},"link":"","children":[]}]}]}]}]}],"apiVersion":"1.3","edges":[],"attributeTypes":{},"blacklist":[]},"checksum":"191951a170303febfececd7814937d67"}

running .\ccsh merge demo.cc.json demo2.cc.jcon -o demo_merged.cc.json produces the error.

csvimport or svnlogparser run just fine.

**Comment by ce-bo** [comment]
Thank you @FlorianHoldt. There seems to be an error while checking if the output file should be printed zipped or as json.
Would you like to have a look into that and maybe create a PR to fix it? :-)

**Comment by FlorianHoldt** [comment]
@ce-bo While I would very much like to do that, java is not really my area of expertese, so'll have to pass on that :/

**Comment by ce-bo** [comment]
After a first investigation, the method "readNBytes" has a different signature in different Java versions (8, 9, 11). 
In Java 11 the ccsh command is working properly. As a workaround you could switch to Java 11. We will continue finding a solution for that.

**Comment by FlorianHoldt** [comment]
Thank you for the fix, very much appreciated!
